package migrationplan

import (
	"bytes"
	"fmt"
	"os"
)

func WriteManifestLock(path string, entries []LockEntry) error {
	var sourceWidth int
	for _, e := range entries {
		if len(e.Source) > sourceWidth {
			sourceWidth = len(e.Source)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("# Code generated by build-migrations. DO NOT EDIT.\n\n")

	for _, e := range entries {
		line := fmt.Sprintf(
			"%s | %-*s | %s\n",
			e.Version,
			sourceWidth,
			e.Source,
			e.Output,
		)
		buf.WriteString(line)
	}

	return os.WriteFile(path, buf.Bytes(), 0o644)
}
