package http

import "github.com/danielgtaylor/huma/v2"

var createChannelOp = huma.Operation{OperationID: "create-channel", Method: "POST", Path: "/groups/{group_id}/channels", Tags: []string{"Collab"}, Summary: "Create group channel", Security: []map[string][]string{{"bearerAuth": {}}}}
var listChannelsOp = huma.Operation{OperationID: "list-channels", Method: "GET", Path: "/groups/{group_id}/channels", Tags: []string{"Collab"}, Summary: "List group channels", Security: []map[string][]string{{"bearerAuth": {}}}}
var createMessageOp = huma.Operation{OperationID: "create-message", Method: "POST", Path: "/channels/{channel_id}/messages", Tags: []string{"Collab"}, Summary: "Create channel message", Security: []map[string][]string{{"bearerAuth": {}}}}
var listMessagesOp = huma.Operation{OperationID: "list-messages", Method: "GET", Path: "/channels/{channel_id}/messages", Tags: []string{"Collab"}, Summary: "List channel messages", Security: []map[string][]string{{"bearerAuth": {}}}}
var updateMessageOp = huma.Operation{OperationID: "update-message", Method: "PATCH", Path: "/channels/{channel_id}/messages/{message_id}", Tags: []string{"Collab"}, Summary: "Update channel message", Security: []map[string][]string{{"bearerAuth": {}}}}
var deleteMessageOp = huma.Operation{OperationID: "delete-message", Method: "DELETE", Path: "/channels/{channel_id}/messages/{message_id}", Tags: []string{"Collab"}, Summary: "Delete channel message", Security: []map[string][]string{{"bearerAuth": {}}}}
var createAttachmentUploadOp = huma.Operation{OperationID: "create-channel-attachment-upload", Method: "POST", Path: "/channels/{channel_id}/attachments/uploads", Tags: []string{"Collab"}, Summary: "Create presigned upload for channel attachment", Security: []map[string][]string{{"bearerAuth": {}}}}
var updateReadCursorOp = huma.Operation{OperationID: "update-read-cursor", Method: "POST", Path: "/channels/{channel_id}/read-cursor", Tags: []string{"Collab"}, Summary: "Update channel read cursor", Security: []map[string][]string{{"bearerAuth": {}}}}
var toggleReactionOp = huma.Operation{OperationID: "toggle-message-reaction", Method: "POST", Path: "/channels/{channel_id}/reactions", Tags: []string{"Collab"}, Summary: "Toggle message reaction", Security: []map[string][]string{{"bearerAuth": {}}}}
var createGuestInviteOp = huma.Operation{OperationID: "create-guest-invite", Method: "POST", Path: "/channels/{channel_id}/guest-invites", Tags: []string{"Collab"}, Summary: "Create guest invite for channel", Security: []map[string][]string{{"bearerAuth": {}}}}
var exchangeGuestInviteOp = huma.Operation{OperationID: "exchange-guest-invite", Method: "POST", Path: "/guest-invites/{token}/exchange", Tags: []string{"Collab"}, Summary: "Exchange guest invite magic link"}
var createConferenceOp = huma.Operation{OperationID: "create-conference", Method: "POST", Path: "/channels/{channel_id}/conferences", Tags: []string{"Collab"}, Summary: "Create channel conference", Security: []map[string][]string{{"bearerAuth": {}}}}
var listConferencesOp = huma.Operation{OperationID: "list-conferences", Method: "GET", Path: "/channels/{channel_id}/conferences", Tags: []string{"Collab"}, Summary: "List channel conferences", Security: []map[string][]string{{"bearerAuth": {}}}}
var createConferenceJoinTokenOp = huma.Operation{OperationID: "create-conference-join-token", Method: "POST", Path: "/conferences/{conference_id}/join-token", Tags: []string{"Collab"}, Summary: "Create Jitsi join token", Security: []map[string][]string{{"bearerAuth": {}}}}
var startConferenceRecordingOp = huma.Operation{OperationID: "start-conference-recording", Method: "POST", Path: "/conferences/{conference_id}/recording/start", Tags: []string{"Collab"}, Summary: "Mark conference recording start", Security: []map[string][]string{{"bearerAuth": {}}}}
var stopConferenceRecordingOp = huma.Operation{OperationID: "stop-conference-recording", Method: "POST", Path: "/conferences/{conference_id}/recording/stop", Tags: []string{"Collab"}, Summary: "Mark conference recording stop", Security: []map[string][]string{{"bearerAuth": {}}}}
var getConferenceTranscriptOp = huma.Operation{OperationID: "get-conference-transcript", Method: "GET", Path: "/conferences/{conference_id}/transcript", Tags: []string{"Collab"}, Summary: "Get conference transcript", Security: []map[string][]string{{"bearerAuth": {}}}}
var jitsiWebhookOp = huma.Operation{OperationID: "jitsi-webhook", Method: "POST", Path: "/integration/jitsi/webhooks", Tags: []string{"Collab"}, Summary: "Ingest Jitsi integration event"}
