name: collabsphere

services:
  master:
    image: chrislusf/seaweedfs:${STORAGE_S3_IMAGE_VERSION}
    env_file:
      - env/.env.dev
      - env/.env.storage.dev
    volumes:
      - ./scripts/seaweedfs:/bootstrap:ro
    entrypoint: [ "/bin/sh", "/bootstrap/seaweedfs-master.sh" ]
    restart: unless-stopped
    networks:
      - internal.network
    ports:
      - "${STORAGE_MASTER_HOST_PORT}:9333"
      - "${STORAGE_MASTER_GRPC_HOST_PORT}:19333"
      - "${STORAGE_MASTER_METRICS_HOST_PORT}:9324"

  volume:
    image: chrislusf/seaweedfs:${STORAGE_S3_IMAGE_VERSION}
    env_file:
      - env/.env.dev
      - env/.env.storage.dev
    volumes:
      - ./scripts/seaweedfs:/bootstrap:ro
      - storage.volume.data:/data
    entrypoint: [ "/bin/sh", "/bootstrap/seaweedfs-volume.sh" ]
    restart: unless-stopped
    networks:
      - internal.network
    ports:
      - "${STORAGE_VOLUME_HOST_PORT}:8080"
      - "${STORAGE_VOLUME_GRPC_HOST_PORT}:18080"
      - "${STORAGE_VOLUME_METRICS_HOST_PORT}:9325"
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs:${STORAGE_S3_IMAGE_VERSION}
    env_file:
      - env/.env.dev
      - env/.env.storage.dev
    volumes:
      - ./scripts/seaweedfs:/bootstrap:ro
      - storage.filer.data:/data
    entrypoint: [ "/bin/sh", "/bootstrap/seaweedfs-filer.sh" ]
    restart: unless-stopped
    networks:
      - internal.network
    ports:
      - "${STORAGE_FILER_HOST_PORT}:8888"
      - "${STORAGE_FILER_GRPC_HOST_PORT}:18888"
      - "${STORAGE_FILER_METRICS_HOST_PORT}:9326"
    depends_on:
      - master
      - volume

  s3:
    image: chrislusf/seaweedfs:${STORAGE_S3_IMAGE_VERSION}
    env_file:
      - env/.env.dev
      - env/.env.storage.dev
    volumes:
      - ./scripts/seaweedfs:/bootstrap:ro
    entrypoint: [ "/bin/sh", "/bootstrap/seaweedfs-s3.sh" ]
    restart: unless-stopped
    secrets:
      - s3_access_key
      - s3_secret_key
    networks:
      - internal.network
    ports:
      - "${STORAGE_S3_HOST_PORT}:8333"
      - "${STORAGE_S3_METRICS_HOST_PORT}:9327"
    depends_on:
      - master
      - volume
      - filer

  bucket-init:
    image: chrislusf/seaweedfs:${STORAGE_S3_IMAGE_VERSION}
    env_file:
      - env/.env.dev
      - env/.env.storage.dev
    volumes:
      - ./scripts/seaweedfs:/bootstrap:ro
    entrypoint: [ "/bin/sh", "/bootstrap/seaweedfs-bucket-init.sh" ]
    networks:
      - internal.network
    depends_on:
      - master
      - filer
      - s3
    restart: "no"


volumes:
  storage.volume.data:
    name: ${STORAGE_VOLUME_DATA_VOLUME:-storage.volume.data}
  storage.filer.data:
    name: ${STORAGE_FILER_DATA_VOLUME:-storage.filer.data}

networks:
  internal.network:
    name: ${INTERNAL_NETWORK_NAME}
    driver: bridge
    external: false

secrets:
  s3_access_key:
    file: secrets/s3/s3_access_key
  s3_secret_key:
    file: secrets/s3/s3_secret_key
