name: collabsphere

services:
  api:
    profiles: [ "local", "prod" ]
    image: colabsphere-api:${IMAGE_TAG}
    restart: unless-stopped
    build:
      context: ../platform
      dockerfile: ../platform/Dockerfile
    env_file:
      - .env.dev
    secrets:
      - dev_password
      - neon_password
      - jwt_secret_key
      - s3_access_key
      - s3_secret_key
    networks:
      - internal.network
      - external.network
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    command: [ "/api" ]
    depends_on:
      postgres:
        condition: service_healthy

networks:
  internal.network:
    name: ${INTERNAL_NETWORK_NAME}
    driver: bridge
    external: false
  external.network:
    name: ${EXTERNAL_NETWORK_NAME}
    external: true

secrets:
  dev_password:
    file: secrets/postgres/dev/db_password
  neon_password:
    file: secrets/postgres/prod/db_password
  jwt_secret_key:
    file: secrets/jwt/jwt_secret_key
  s3_access_key:
    file: secrets/s3/s3_access_key
  s3_secret_key:
    file: secrets/s3/s3_secret_key
