name: collabsphere

services:
  s3:
    profiles: [ "local" ]
    image: collabsphere-garage:${STORAGE_S3_GARAGE_IMAGE_VERSION:-v1.3.1}
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile.garage
      args:
        GARAGE_VERSION: ${STORAGE_S3_GARAGE_IMAGE_VERSION:-v1.3.1}
    restart: unless-stopped
    env_file:
      - .env.dev
    secrets:
      - s3_garage_rpc_secret
    networks:
      - internal.network
    ports:
      - "${STORAGE_S3_PORT:-9000}:${STORAGE_S3_PORT:-9000}"
    volumes:
      - ./scripts:/bootstrap:ro
      - s3.data:/var/lib/garage
    entrypoint: ["/bin/sh", "/bootstrap/garage-entrypoint.sh"]

  s3-init:
    profiles: [ "local" ]
    image: collabsphere-garage:${STORAGE_S3_GARAGE_IMAGE_VERSION:-v1.3.1}
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile.garage
      args:
        GARAGE_VERSION: ${STORAGE_S3_GARAGE_IMAGE_VERSION:-v1.3.1}
    restart: "no"
    env_file:
      - .env.dev
    depends_on:
      - s3
    secrets:
      - s3_garage_rpc_secret
    networks:
      - internal.network
    volumes:
      - ./scripts:/bootstrap:ro
      - s3.data:/var/lib/garage
      - s3.credentials:/run/generated/s3
    entrypoint: ["/bin/sh", "/bootstrap/garage-init.sh"]

volumes:
  s3.data:
    name: s3.data
  s3.credentials:
    name: s3.credentials

networks:
  internal.network:
    name: internal.network
    driver: bridge
    external: false

secrets:
  s3_garage_rpc_secret:
    file: secrets/s3/garage_rpc_secret