name: collabsphere

services:
  api:
    profiles: [ "local", "prod" ]
    image: colabsphere-api:${IMAGE_TAG}
    restart: unless-stopped
    build:
      context: ../platform
      dockerfile: ../platform/Dockerfile
    env_file:
      - .env.dev
    secrets:
      - dev_password
      - neon_password
      - jwt_secret
      - s3_access_key
      - s3_secret
    networks:
      - internal.network
      - web.network
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    command: [ "/api" ]
    depends_on:
      postgres:
        condition: service_healthy
      s3:
        condition: service_started
      s3-init:
        condition: service_completed_successfully

networks:
  internal.network:
    name: internal.network
    driver: bridge
    external: false
  web.network:
    name: web.network
    external: true

secrets:
  dev_password:
    file: deploy/secrets/postgres/dev/db_password
  neon_password:
    file: deploy/secrets/postgres/prod/db_password
  jwt_secret:
    file: deploy/secrets/jwt/jwt_secret
  s3_access_key:
    file: deploy/secrets/s3/s3_access_key
  s3_secret:
    file: deploy/secrets/s3/s3_secret
