name: collabsphere

services:
  prometheus:
    profiles: [ "observability" ]
    image: prom/prometheus:v2.21.0
    restart: unless-stopped
    ports:
      - "9000:9090"
    volumes:
      - ./observability/prometheus:/etc/prometheus:ro
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
