name: collabsphere

services:
  api:
    profiles: [ "local", "prod" ]
    image: colabsphere-api:${IMAGE_TAG}
    restart: unless-stopped
    build:
      context: ../platform
      dockerfile: ../platform/Dockerfile
    env_file:
      - .env.dev
    secrets:
      - dev_password
      - neon_password
      - jwt_secret
    networks:
      - internal.network
      - web.network
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:8080/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    command: [ "/api" ]
    depends_on:
      postgres:
        condition: service_healthy
      s3:
        condition: service_started
      s3-init:
        condition: service_completed_successfully
    volumes:
      - s3.credentials:/run/generated/s3:ro

networks:
  internal.network:
    name: internal.network
    driver: bridge
    external: false
  web.network:
    name: web.network
    external: true

volumes:
  s3.credentials:
    name: s3.credentials

secrets:
  dev_password:
    file: secrets/postgres/dev/password
  neon_password:
    file: secrets/postgres/prod/password
  jwt_secret:
    file: secrets/jwt/secret
