name: collabsphere

services:
  zitadel-db:
    profiles: [ "local" ]
    image: postgres:18.3-trixie
    restart: unless-stopped
    secrets:
      - zitadel_postgres_admin_password
    environment:
      PGUSER: postgres
      POSTGRES_DB: zitadel
      POSTGRES_PASSWORD_FILE: /run/secrets/zitadel_postgres_admin_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d zitadel -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    ports:
      - "${ZITADEL_POSTGRES_HOST_PORT}:5432"
    volumes:
      - zitadel.postgres.data:/var/lib/postgresql
    networks:
      - zitadel.network

  zitadel:
    profiles: [ "local" ]
    image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION}
    restart: unless-stopped
    secrets:
      - zitadel_master_key
      - zitadel_admin_token
      - zitadel_runtime_secrets_yaml
      - zitadel_init_steps_yaml
    user: "0"
    command:
      - start-from-init
      - --masterkeyFile
      - /run/secrets/zitadel_master_key
      - --config
      - /run/secrets/zitadel_runtime_secrets_yaml
      - --steps
      - /run/secrets/zitadel_init_steps_yaml
      - --tlsMode
      - disabled
    environment:
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_DOMAIN}
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE}
      ZITADEL_TLS_ENABLED: "false"
      ZITADEL_DATABASE_POSTGRES_HOST: zitadel-db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: ${ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED}
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: ${ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI}
      ZITADEL_OIDC_DEFAULTLOGINURLV2: ${ZITADEL_OIDC_DEFAULTLOGINURLV2}
      ZITADEL_OIDC_DEFAULTLOGOUTURLV2: ${ZITADEL_OIDC_DEFAULTLOGOUTURLV2}
      ZITADEL_SAML_DEFAULTLOGINURLV2: ${ZITADEL_SAML_DEFAULTLOGINURLV2}
    healthcheck:
      test: [ "CMD", "/app/zitadel", "ready" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 20s
    ports:
      - "${ZITADEL_HOST_PORT}:8080"
      - "${ZITADEL_LOGIN_HOST_PORT}:3000"
    volumes:
      - zitadel.shared:/zitadel
    networks:
      zitadel.network:
        aliases:
          - ${ZITADEL_DOMAIN}
      external.network:
        aliases:
          - ${ZITADEL_DOMAIN}
    depends_on:
      zitadel-db:
        condition: service_healthy

  zitadel-login:
    profiles: [ "local" ]
    image: ghcr.io/zitadel/zitadel-login:${ZITADEL_LOGIN_VERSION}
    restart: unless-stopped
    user: "0"
    environment:
      ZITADEL_API_URL: http://${ZITADEL_DOMAIN}:8080
      NEXT_PUBLIC_BASE_PATH: /ui/v2/login
      ZITADEL_SERVICE_USER_TOKEN_FILE: /zitadel/login-client.pat
    network_mode: service:zitadel
    volumes:
      - zitadel.shared:/zitadel
    depends_on:
      zitadel:
        condition: service_healthy

volumes:
  zitadel.postgres.data:
    name: zitadel.postgres.data
  zitadel.shared:
    name: zitadel.shared

networks:
  zitadel.network:
    name: zitadel.network
    driver: bridge
    external: false
  external.network:
    name: ${EXTERNAL_NETWORK_NAME}
    external: true

secrets:
  zitadel_postgres_admin_password:
    file: secrets/identity/zitadel_postgres_admin_password
  zitadel_postgres_admin_token:
    file: secrets/identity/zitadel_postgres_admin_token
  zitadel_master_key:
    file: secrets/identity/zitadel_master_key
  zitadel_runtime_secrets_yaml:
    file: secrets/identity/zitadel_runtime_secrets.yaml
  zitadel_init_steps_yaml:
    file: secrets/identity/zitadel_init_steps.yaml
  zitadel_admin_token:
    file: secrets/identity/zitadel_admin_token
