name: collabsphere

services:
  postgres-test:
    profiles: ["test"]
    image: postgres:18.3-trixie
    restart: unless-stopped
    hostname: "${TEST_POSTGRES_HOST}"
    networks:
      - internal.network
    env_file:
      - ../env/.env.postgres.test
    environment:
      POSTGRES_DB: "${TEST_POSTGRES_DB}"
      POSTGRES_USER: "${TEST_POSTGRES_USER}"
      POSTGRES_PASSWORD_FILE: "${TEST_POSTGRES_PASSWORD_FILE}"
    secrets:
      - test_postgres_password
    healthcheck:
      test: ["CMD-SHELL", "sh /opt/healthcheck/postgres-test.sh"]
      interval: 3s
      timeout: 3s
      retries: 20
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    volumes:
      - postgres.data.test:/var/lib/postgresql
      - ../scripts/healthcheck/postgres-test.sh:/opt/healthcheck/postgres-test.sh:ro

volumes:
  postgres.data.test:
    name: "postgres.data_test"

networks:
  internal.network:
    name: ${INTERNAL_NETWORK_NAME}
    driver: bridge
    external: false

secrets:
  test_postgres_password:
    file: ../secrets/postgres/test/db_password
